select * from estado;

CREATE TABLE ESTADO (ATRIBUTO VARCHAR2(10), VALOR NUMBER(2));
INSERT INTO ESTADO VALUES ('MOTOR',0);
INSERT INTO ESTADO VALUES ('EIXO X',0);
INSERT INTO ESTADO VALUES ('EIXO Y',0);

drop table estado